### ISSUE TITLE
Wiring difficult to make out

### ISSUE THREAD

**Issue by kybernetikos** [rmcgibbo/Jarvis#1]
Hi,  I really like what you've done here and am interested in building or acquiring my own. 

I did look at the photo but I wonder if you would mind explaining the wiring in more detail?

**Comment by rmcgibbo** [comment]
Lol cool! I didn't really expect anyone else to use this, but I'm pleased.

**Comment by rmcgibbo** [comment]
The basic idea with the wiring is that I wired up the two ethernet jacks directly (pin 1 -> pin 1, pin 2 -> 2, etc) so that any signals are just passively passed-through, and then I also connected a couple of the ethernet pins to the board in order to inject some extra signals into the stream (and to snoop on the signals being passed). I'll try to make a proper drawing after work.

**Comment by rmcgibbo** [comment]
Basically other than the direct connection of the two ethernet jacks, the other wiring is reflected here in code.
https://github.com/rmcgibbo/Jarvis/blob/master/src/JarvisDesk.cpp#L5-L9

Here's the pinout of my ESP8266 board: https://learn.adafruit.com/assets/46249

So I have:
* pin 4 on the board connected to pin 8 on the RJ45 jacks;
* pin 5 on the board connected to pin 7 on the RJ45 jacks;
* pin 13 on the board connected to pin 6 on the RJ45 jacks;
* pin 14 on the board connected to pin 1 on the RJ45 jacks;
* pin 12 on the board connected to pin 2 on the RJ45 jacks;

Furthermore, I have pin 3 on the RJ45 jack connected to GND on the board (following https://github.com/phord/Jarvis#readme) and pin 5 on the RJ45 jack connected to the "USB" pin on the board, for 3.3V power.

**Comment by kybernetikos** [comment]
Thanks so much for this

**Comment by rmcgibbo** [comment]
By way of full disclosure: I do use this system on a daily basis (I have a curl command integrated into my menu bar to send the raise/lower command to the device via adafruit-io). The most brittle part of the system has been the wifi on the chip, which sometimes becomes disconnected (despite being < 6 feet from the router). I don't know if this is due to congestion on the 2.4G band, or something else, but it usually requires rebooting the device and sometimes resetting the static ip assignment i've given it on the router. It disconnects perhaps once per month. If I were going to build the device again I might consider a wired setup though.

**Comment by kybernetikos** [comment]
Thanks for that. For anyone else wanting to build one, I was just reading the details and I see that powering the feather like that is probably fine but it would be bad to plug it into USB while powered.

The other question I have is that the feather docs explicitly say that the gpio pins are 3.3v and not 5v safe, but the jarvis system seems to be 5v. Did you do anything around that to make it work OK?

**Comment by rmcgibbo** [comment]
I didn’t. Also I do plug it into usb while powered like this. :/ Maybe that’s why the wifi is spotty :)
